meta_product_name: "Komod'"
meta_title: "Komod' - Le dressing illimité sans culpabilité"
meta_description: "Komod', une application type réseau social où les utilisateurs se rencontrent pour s'échanger des vêtements"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@komod_twitter_account"  required for Twitter Cards
